### PR TITLE
Fix Tool Cache for Self Hosted Runners

### LINKED ISSUE #459: Cannot create directory ‘/opt/hostedtoolcache’ after recent release
**Description:**

The following error start happening after the recent action release:

```
2022-07-12T14:12:47.7158848Z ##[group]Run actions/setup-python@v4
2022-07-12T14:12:47.7159230Z with:
2022-07-12T14:12:47.7159527Z   python-version: 3.x
2022-07-12T14:12:47.7160059Z   token: ***
2022-07-12T14:12:47.7160394Z   update-environment: true
2022-07-12T14:12:47.7162682Z ##[endgroup]
2022-07-12T14:12:48.0166854Z Version 3.x was not found in the local cache
2022-07-12T14:12:48.3072207Z Version 3.x is available for downloading
2022-07-12T14:12:48.3074130Z Download from "https://github.com/actions/python-versions/releases/download/3.10.5-2452607758/python-3.10.5-linux-20.04-x64.tar.gz"
2022-07-12T14:12:49.1279090Z Extract downloaded archive
2022-07-12T14:12:49.1380950Z [command]/usr/bin/tar xz --warning=no-unknown-keyword -C /actions-runner/_work/_temp/2d83bfeb-a252-4083-95bf-6f30cffc5507 -f /actions-runner/_work/_temp/c2619dbf-23ad-46f0-9b07-baf06258c9c8
2022-07-12T14:12:52.2679935Z Execute installation script
2022-07-12T14:12:52.2887302Z Check if Python hostedtoolcache folder exist...
2022-07-12T14:12:52.2888180Z Creating Python hostedtoolcache folder...
2022-07-12T14:12:52.2921018Z ##[error]mkdir:
2022-07-12T14:12:52.2937518Z ##[error]cannot create directory ‘/opt/hostedtoolcache’
2022-07-12T14:12:52.2939104Z ##[error]: Permission denied
2022-07-12T14:12:52.2941609Z ##[error]The process '/usr/bin/bash' failed with exit code 1
2022-07-12T14:12:52.3294942Z Post job cleanup.
```

**Action version:**

v4

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**

- 3.10.5

**Repro steps:**  

```
  setup-python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
```

**Expected behavior:**

Won't error.

**Actual behavior:**

It errors.

### PR DESCRIPTION
**Pull request by techman83**
**Description:**
As of actions/python-versions@f75c0e6e4b33d1d070936b35d682b7c9efceaa4b the default location for Linux/Mac/Windows was aligned to default to `RUNNER_TOOL_CACHE` if `AGENT_TOOLCACHE` wasn't specified. The change introduced and released in v4.1.0 didn't account for this default being different for self hosted runners and hard coded it to `/opt/hostedtoolcache`.

This change aligns the behaviour of `actions/setup-python` with `action/python-versions`, and makes the experience of using the action the same on both hosted + self-hosted runners.

I have adjusted the documentation, and made the changes in line with how the project appears to operate, but as shouldn't be much of a surprise, TypeScript isn't my day-to-day language :slightly_smiling_face: and welcome any feedback.

If there are test cases that can be added, happy for some guidance, but I didn't see any with the commit that changed this behaviour. From my manual testing, both hosted + self-hosted work as I would expect.

Hosted Linux
```
Requirement already satisfied: setuptools in /opt/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)`
```

Hosted Windows
```
Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (58.1.0)
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (22.0.4)
Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.0-beta.4\x64\lib\site-packages (22.0.4)
```

Hosted Mac
```
Requirement already satisfied: setuptools in /Users/runner/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
```

Self-Hosted Linux
```
Requirement already satisfied: setuptools in /home/actions/actions-runner/_work/_tool/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (58.1.0)
Requirement already satisfied: pip in /home/actions/actions-runner/_work/_tool/Python/3.11.0-beta.4/x64/lib/python3.11/site-packages (22.0.4)
```

**Related issue:**
Fixes #459 

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by IvanZosimov** [comment]
Hi, @techman83 👋 ! Thank you for your contribution! Please, read this part of the setup-python [README.md](https://github.com/actions/setup-python#linux) file again. The main sense here is:
The Python packages that are downloaded from actions/python-versions are originally compiled from source in `/opt/hostedtoolcache/` directory with the [--enable-shared](https://github.com/actions/python-versions/blob/94f04ae6806c6633c82db94c6406a16e17decd5c/builders/ubuntu-python-builder.psm1#L35) flag, which makes them **non-relocatable**. It means that on the runner, Python should be placed on the same directory `/opt/hostedtoolcache/` in order to work properly. It's just a matter of chance that in your case with location `/home/actions/actions-runner/_work/_tool` it works as expected. In fact, we had a lot of issues when users forgot to set `ACTION_TOOLSDIRECTORY`, installed Python into the path that was different from `/opt/hostedtoolcache/` and got issues with it. But now functionality for setting this variable automatically is added, all you need just to configure `/opt/hostedtoolcache/` folder and check required permissions. 

We understand that sometimes there could be a problem to use `/opt/hostedtoolcache/` because of the lack of permissions. In that case, you can configure `AGENTS_TOOLDIRECTORY` variable with any path that suits you, but you have to understand that you're taking a risk of getting unpredictable issues.

By now I'm going to close this PR, if you have any questions feel free to ping us here or in the mentioned above issue.

**Comment by techman83** [comment]
@IvanZosimov I have read that section of the readme a number of times, whilst I hear and appreciate what you are saying, that interpretation as far as I can gather is incorrect.

This change was to fix an issue with `actions/python-versions`, that was already corrected in 2020 -> https://github.com/actions/python-versions/commit/f75c0e6e4b33d1d070936b35d682b7c9efceaa4b

The directions in the readme make using `actions/setup-python` far more complex than they need to be, and you will find that most consumers of this action will miss that step as it "just works" for hosted.

Personally it will be easy for me to adjust our runner permissions, but if I didn't have that level of control over them, I would have to go to every work flow and reset the runner cache back using an environment variable attached pointing to the runner context.

```yaml
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        env:
          AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0-beta.4"
          cache: pip
```

**Comment by techman83** [comment]
I won't spam open PRs, but I did realise even setting the `AGENT_TOOLSDIRECTORY` was unnecessary. I have the diff [here](https://github.com/actions/setup-python/compare/main...techman83:setup-python:fix/self_hosted) and a demonstration [here](https://github.com/Effortless-Networking/test-setup-python/runs/7384473653)

**Comment by IvanZosimov** [comment]
Hi, @techman83 👋 First of all I'd like to thank you for your contribution and willingness to improve our action ❤️ Your questions made us to make [deeper investigation](https://github.com/actions/setup-python/issues/459#issuecomment-1187418327). May I ask you to revive this PR?

**Comment by techman83** [comment]
@IvanZosimov sure thing! I'll raise a new PR, I learned more about what was happening and I had definitely had a misunderstanding about what the #394 was intended to fix. So I have made some improvements with that in mind :slightly_smiling_face:

**Pull request closed without merging**
