### PR TITLE
Added action output python-install-dir

### PR DESCRIPTION
**Pull request by arBmind**
**Description:**
* Added action output python-install-dir
* also fixed export of python-version for pypy installs

**Related issue:**
Add link to the related issue.

**Check list:**
- [x] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by nikita-bykov** [comment]
Hello @arBmind, thanks for your PR!
Could you please describe in more details what this new output is for?
After using the action, `pythonLocation` environment variable is available with the following values:
Windows - `C:\hostedtoolcache\windows\Python\3.10.1\x64`
macOS - `/Users/runner/hostedtoolcache/Python/3.10.0/x64`
Ubuntu - `/opt/hostedtoolcache/Python/3.10.1/x64`
Does this variable meets your needs?

**Comment by arBmind** [comment]
Hi @nikita-bykov,
Thank you for considering my pull request.
I use the patched version here for my QtCreator build. https://github.com/arBmind/qt-creator/blob/patched/6.0/.github/workflows/build_qbs.yml#L73
The environment `PYTHON_INSTALL_DIR` is usually provided to customize the python install location. This folder contains the python executable.

**Comment by arBmind** [comment]
I checked the code again. It seems you are right. The exported environment `pythonLocation` is the correct location. I was not aware that you can export environment variables like that.
It may be a good idea to document this variable or did I miss this also? Will try to change my QtCreator run next.

**Comment by arBmind** [comment]
I tested the env variable: `pythonLocation` and It works for my use case. 

This PR is no longer needed.

**Pull request closed without merging**
