### PR TITLE
Enable TypeScript declaration files

### PR DESCRIPTION
**Pull request by bexnoss**
**Description:**
This PR enables the generation of TypeScript declaration files.

**Related issue:**
Improves the workaround from https://github.com/actions/setup-python/issues/38#issuecomment-634471245.

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by bexnoss** [comment]
I didn't notice that dist/ is tracked. This also simplifies the workaround in https://github.com/actions/setup-python/issues/38. Thanks for the heads up!

**Comment by bexnoss** [comment]
This is blocked by the usage of ncc for building. See https://github.com/actions/setup-python/pull/306

**Comment by dmitry-shibanov** [comment]
Hello @bexnoss. Thank you for your pull request. Would the initial issue be resolved by changing the build command to: `tsc && ncc build -o dist/setup src/setup-python.ts && ncc build -o dist/cache-save src/cache-save.ts`?

**Comment by bexnoss** [comment]
> Hello @bexnoss. Thank you for your pull request. Would the initial issue be resolved by changing the build command to: `tsc && ncc build -o dist/setup src/setup-python.ts && ncc build -o dist/cache-save src/cache-save.ts`?

Hello, yes running tsc is what's missing for the workaround from https://github.com/actions/setup-python/issues/38 to work.

**Comment by bexnoss** [comment]
Superseded by https://github.com/actions/setup-python/pull/329

**Pull request closed without merging**
