### PR TITLE
Force TOOLCACHE_ROOT to be equal AGENT_TOOLSDIRECTORY

### PR DESCRIPTION
**Pull request by dsame**
**Description:**
The AGENT_TOOLSDIRECTORY variable tells where python has to be installed to
The RUNNER_TOOL_CACHE variable tells where python expected to be installed in

If these 2 variables are different the `actions/tool-cache.find` does not find a python instance installed by `actions/setup-pyton.installCpythonFromRelease`

Test build for self-hosted agent with AGENT_TOOLSDIRECTORY set(the original issue condition): https://github.com/akv-demo/setup-python-test/runs/5237321231?check_suite_focus=true

Test for builds for hosted agents (with AGENT_TOOLSDIRECTORY set and omitted)

https://github.com/akv-demo/setup-python-test/runs/5237321104?check_suite_focus=true
https://github.com/akv-demo/setup-python-test/runs/5237321426?check_suite_focus=true

Upd: last changes sample builds https://github.com/akv-demo/setup-python-test/actions/runs/1874490317

**Note:**
It seems we should not apply this fix but remove the mention of AGENT_TOOLSDIRECTORY from the documentation. In this case the python will be installed into `_work/_tool/Python/3.7.7/x64` directory

see https://github.com/akv-demo/setup-python-test/runs/5237321176?check_suite_focus=true

**Related issue:**
[Add link to the related issue.](https://github.com/actions/setup-python/issues/162)

**Check list:**
- [ ] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by nialloh23** [comment]
Just wondering if there is an idea of when this PR will be merged? And if it fixes the issues seen setting up pyhon versions on self hosted runners? Thanks a mill

**Comment by Nick-Yazdani** [comment]
> Just wondering if there is an idea of when this PR will be merged? And if it fixes the issues seen setting up pyhon versions on self hosted runners? Thanks a mill

Yeah having this same issue and it would be great to get this PR merged

**Review by dmitry-shibanov — APPROVED** [review]

**Review by brcrista — CHANGES_REQUESTED** [review]
Ooooh ... this is confusing.  Here's how these variables work:
- The runner looks for a [number of variables](https://github.com/actions/runner/blob/28f002793854c69cc666029e81061f54002ae927/src/Runner.Common/HostContext.cs#L262) for historical reasons, but prefers `RUNNER_TOOL_CACHE`.
- The script that pre-populates the tools cache with Python versions [works with both](https://github.com/actions/python-versions/blob/7e0253ff52984c54607f0f79a1fbbf0f9b926fde/installers/nix-setup-template.sh#L13).
- The actions toolkit [looks for `RUNNER_TOOL_CACHE`](https://github.com/actions/toolkit/blob/a1b068ec31a042ff1e10a522d8fdf0b8869d53ca/packages/tool-cache/src/tool-cache.ts), [not `AGENT_TOOLSDIRECTORY`](https://github.com/actions/toolkit/search?q=AGENT_TOOLSDIRECTORY).  This is what `setup-python` uses to get the version.

> It seems we should not apply this fix but remove the mention of AGENT_TOOLSDIRECTORY from the documentation. In this case the python will be installed into `_work/_tool/Python/3.7.7/x64` directory

I think you're right about this.  Some relevant discussion from when the docs were written: https://github.com/actions/setup-python/pull/90#discussion_r422323846

More specifically, **I think the right fix is to replace `AGENT_TOOLSDIRECTORY` with `RUNNER_TOOL_CACHE` in the README**.  Could you try testing that and see if it works?

cc @konradpabjan since you might have some additional context

**Comment by dsame** [comment]
@brcrista 
Hello Brian, it seems i got the idea why the variable  AGENT_TOOLSDIRECTORY  was introduced and we need to merge this PR.

This variable is useful if an user wants to install the python to the other location than the default `_work/_tool/Python/3.7.7/x64` 

I [tried](https://github.com/akv-demo/setup-python-test/actions/runs/2108628255) to set `RUNNER_TOOL_CACHE` instead of `AGENT_TOOLSDIRECTORY` as you advised but it is ignored and the python is installed in its default location `_work/_tool/Python/3.7.7/x64`

Summary: i am 90% sure we need both apply the fix of this PR and make a change in the docs to make clear AGENT_TOOLSDIRECTORY is an optional variable and should be used only if an user wants to change the default locations

**Review by brcrista — APPROVED** [review]
Hm, ok, I guess there's something I'm missing then.  Let's go ahead and merge this.

Using the legacy variable isn't ideal, but the most important thing is to have it documented correctly.  So if you could just follow up with a change to the docs, that would be great.

**Comment by dsame** [comment]
> Hm, ok, I guess there's something I'm missing then. Let's go ahead and merge this.
> 
> Using the legacy variable isn't ideal, but the most important thing is to have it documented correctly. So if you could just follow up with a change to the docs, that would be great.

And the last note - i've checked the existing README and the wording "The Python packages that are downloaded from `actions/python-versions` are originally compiled from source in `/opt/hostedtoolcache/` ... which makes them non-relocatable." explains the AGENT_TOOLSDIRECTORY is not optional and nothing in README should be changed. So we end up with merging this PR.

**Comment by brcrista** [comment]
In that case, I wonder if it would just make sense to force `AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache/` in this action?

Anyway @dsame @dmitry-shibanov feel free to merge when ready.

**Review by marko-zivic-93 — APPROVED** [review]

**Comment by dsame** [comment]
> In that case, I wonder if it would just make sense to force `AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache/` in this action?
> 
> Anyway @dsame @dmitry-shibanov feel free to merge this PR when you're ready.

helllo @brcrista ,

I agree  the current configuration is overcomplicated, but i asked to @marko-zivic-93 to merge this PR asap because we have many related issue.

I'll create the another PR soon to eliminate we need of the set the AGENT_TOOLSDIRECTORY for self-hosted agents

**Pull request merged**
