### PR TITLE
FIX: Extract zip win

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
**Description:**

Changes consist in reordering extract utils to first attemps ExtractToDirectory and then Expand-Archive. For some reason the download CPython release was not correctly handled by Expand-Archive. This could be happening if the zip file was compressed using an unsupported compression method (e.g. through `zip` with Unix/Linux).

**Related issue:** https://github.com/actions/setup-python/issues/819

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Comment by SMoraisAnsys** [comment]
@priyagupta108 I took the liberty to take a look at #819 and I think this changes should correct the issue. I tested it on my repo and it works fine (didn't do intensive testing though).

**Review by RobPasMue — APPROVED** [review]
This will solve so many issues! Windows self-hosted runners could no longer use "v5" if the Python version requested was not available in the cache or in the system already. We can finally use the action as is without having to stick to "v4" or implement workarounds!

**Comment by SMoraisAnsys** [comment]
I took the liberty to reproduce the error (fixed by this PR) on a github runner. The associated branch (https://github.com/SMoraisAnsys/setup-python/tree/test/no-pwshpath) consists in removing a part of the code of  `function extractZipWin(file, dest)` in order to ensure that the runner uses the failing part of the code.

PR that can be used to oversee the changes : https://github.com/SMoraisAnsys/setup-python/pull/1
Failing CI log : https://github.com/SMoraisAnsys/setup-python/actions/runs/8491166206/job/23262896827?pr=1

**Comment by RobPasMue** [comment]
@actions/setup-actions-team could we get this reviewed and merged soon?

**Comment by jeremyd2019** [comment]
@aparnajyothi-y pointed out in https://github.com/actions/setup-python/issues/819#issuecomment-2100107374 that this code comes from actions/toolkit.  Perhaps a PR against https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts would be better reviewed?

**Comment by SMoraisAnsys** [comment]
> @aparnajyothi-y pointed out in [#819 (comment)](https://github.com/actions/setup-python/issues/819#issuecomment-2100107374) that this code comes from actions/toolkit. Perhaps a PR against https://github.com/actions/toolkit/blob/main/packages/tool-cache/src/tool-cache.ts would be better reviewed?

As you mentioned, the problem seems to be related with `actions/toolkit`. However, the mentioned [PR](https://github.com/actions/toolkit/pull/1552) was created in October 2023. I don't think changes would be better reviewed there.

**Comment by jeremyd2019** [comment]
I hear you, but I think what I meant is that the changes need to be applied there rather than here.  Also, I don't think that linked PR would actually help this case.

**Comment by SMoraisAnsys** [comment]
Closing this since #916 fixed #819 in our CICD.

**Pull request closed without merging**
