### PR TITLE
Support installation specified of Python version for Linux

### PR DESCRIPTION
**Pull request by SerVB**
Follow-up of #29.

I've forked and added support for installing custom version if it's not found.

This implementation is MVP, so:
* only Linux is supported.
* path of installation is needed to be discussed.
* there are no tests (but I've used my forked action in my repo and it works: <https://github.com/SerVB/TheRecentStatOfYou/actions/runs/78111473>).

Can it be accepted to the main repo? I'm ready for discussions!

P.S.: Any ideas how can I fix the problem with unchanged lines marked as changed in this PR? Maybe something related to line endings...

### CODE REVIEW

**Comment by SerVB** [comment]
Oops, will investigate the failed test.

**Comment by SerVB** [comment]
It seems that error in `exec.exec` crashes tests. I've added `try catch` around it, but that doesn't help. Any suggestions?

**Comment by SerVB** [comment]
@konradpabjan, could you help? Or advise a place to ask?

**Comment by konradpabjan** [comment]
@SerVB thanks for the PR! We have something new on the way for `setup-python` that downloads specific versions of python if they are not available. This will allow non-cached versions of python to be installed and it will work with Windows Linux & Mac. It should address the problem you're facing 😀

Check out this PR: https://github.com/actions/setup-python/pull/85

Can you open an issue in [actions/python-versions](https://github.com/actions/python-versions) for the `2.7.7` version of python. 

In your example run it takes about 6 minutes to compile the specific version of Python, while downloading an already compiled package and installing it should take about 10 seconds. In `python-versions` we also compile with `--enable-optimizations` so it takes a lot longer to compile, but the binaries are little bit better so I think the best solution is to get `2.7.7` available in `python-versions`.

**Comment by konradpabjan** [comment]
Sorry that we couldn't get `2.7.7` into `python-versions` 😕 The version is just too old and there were a lot of weird issues during compile time that we can't prioritize at the moment.

Based off of the consensus in https://github.com/actions/virtual-environments/issues/810 I'll close out this PR. Thanks again for initially creating this PR and apologies that we can't support your specific use case.

**Comment by SerVB** [comment]
@konradpabjan , and why don't you want to add a feature to compile any python version manually, as I propose here?

I don't understand why you see only two variants:
* Precompile 2.7.7.
* Don't support 2.7.7 at all.

This PR is not even about 2.7.7, it's more general :) #85 doesn't cover it.

**Comment by konradpabjan** [comment]
@SerVB 

We're trying to keep any compile logic outside of this action. Historically, where/how we compiled Python from source was closed source, however we recently moved everything to `actions/python-versions` and we pull everything from there now and any updates will take place there.

Maintaining compilation in this action and in another place is a maintenance burden that is hard to justify. It would also cause some confusion for users (do they download an already compiled version or do they have to download from source and build it themselves, or do they use an already installed version?).

**Pull request closed without merging**
