### PR TITLE
Update NPM packages

### PR DESCRIPTION
**Pull request by konradpabjan**
Sanity check to make sure everything works before going to master: https://github.com/konradpabjan/Testing2/runs/533477128?check_suite_focus=true

This should make the security warning go away that we're seeing. 

I used `ncu` to update all the packages (haven't found a better way to update all npm packages)
https://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version

Also `npm run format-check` is green on my windows box, but it's failing here?!? looks like it's just line endings so that can be ignored, still curious as to why (I've got CRLF in vscode and `core.autocrlf` set to true for git)?

### CODE REVIEW

**Comment by brcrista** [comment]
Why do we need to update all of the packages?

**Comment by konradpabjan** [comment]
> Why do we need to update all of the packages?

Just going on an update spree. Dependabot has been submitting a few PRs here and there so I figure it's best to keep packages up to date: https://github.com/actions/setup-python/pull/73

**Comment by brcrista** [comment]
> looks like it's just line endings so that can be ignored, still curious as to why (I've got CRLF in vscode and core.autocrlf set to true for git)?

A few tricks here to help:
- You can see the actual line endings in Notepad++ if you show all characters.
- With `core.autocrlf`, you can blow away your working tree (don't delete the `.git` directory of course) and then `git checkout -f konradpabjan/npm-updates` to force line ending normalization on all files.
- To avoid problems in the future, you can add a `.gitattributes` file at the top level of the repo with the following contents:

```
* text=auto
```

`.gitattributes` will override anyone's local Git config, so we don't have to rely on everyone having the same `core.autocrlf` settings.

**Comment by konradpabjan** [comment]
@brcrista figured it out, `* text=auto` is needed along with `eol=lf`. I suspect git might have some different settings during checkout on our runners which is why this weirdness was happening.

I followed the recommendations here: https://prettier.io/docs/en/options.html#end-of-line

**Pull request merged**
